FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY frontend/html/ /usr/share/nginx/html/
COPY frontend/js/ /usr/share/nginx/html/js/
COPY frontend/css/ /usr/share/nginx/html/css/
COPY frontend/assets/ /usr/share/nginx/html/assets/

EXPOSE 80
